---
services:
  github-runner:
    build: .
    image: ghcr.io/yelinaung/homelab/github-runner:latest
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      - REPO_URL=${REPO_URL}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - DISABLE_AUTO_UPDATE=true
