all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    lxc_containers:
      hosts:
        beszel-hub:
          ansible_user: root
        forgejo:
          ansible_user: root
        unpoller:
          ansible_user: root
        readeck:
          ansible_user: root
    other_vms:
      hosts:
        vultr:
          ansible_user: yla
    proxmox:
      hosts:
        homelab1:
          ansible_user: root
        homelab2:
          ansible_user: root
        homelab3:
          ansible_user: root
    vms_on_proxmox:
      hosts:
        grafana:
          ansible_user: ubuntu
        influx:
          ansible_user: ubuntu
        kr-playground-hotel:
          ansible_user: ubuntu
        playground-bravo:
          ansible_user: ubuntu
        ubuntu-alpha:
          ansible_user: ubuntu
        umami:
          ansible_user: ubuntu
        vicky:
          ansible_user: ubuntu
        yankee:
          ansible_user: ubuntu
        immich:
          ansible_user: ubuntu
        dokku1:
          ansible_user: ubuntu
        waung:
          ansible_user: ubuntu
