---
- name: Install vector.dev on the given servers
  hosts: '{{ vm_hosts | default("all")}}'
  become: true
  gather_facts: true
  tasks:
    - name: Install prerequisites packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - curl
          - gnupg
          - xclip
        state: present
        update_cache: true
    - name: Download Vector GPG key
      ansible.builtin.get_url:
        url: https://keys.datadoghq.com/DATADOG_APT_KEY_CURRENT.public
        dest: /tmp/datadog-apt-key.public
        mode: "0644"
    - name: Install Vector GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/datadog-archive-keyring.gpg /tmp/datadog-apt-key.public
        creates: /usr/share/keyrings/datadog-archive-keyring.gpg
    - name: Add Vector apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/datadog-archive-keyring.gpg] https://apt.vector.dev stable vector-0"
        state: present
    - name: Install Vector
      ansible.builtin.apt:
        name: vector
        state: present
        update_cache: true
    - name: Add vector user to docker group
      ansible.builtin.user:
        name: vector
        groups: docker
        append: true
    - name: Deploy Vector config
      ansible.builtin.copy:
        src: configs/vector.yaml
        dest: /etc/vector/vector.yaml
        owner: vector
        group: vector
        mode: "0644"
      notify: Restart Vector
    - name: Enable and start Vector
      ansible.builtin.systemd:
        name: vector
        state: started
        enabled: true
  handlers:
    - name: Restart Vector
      ansible.builtin.systemd:
        name: vector
        state: restarted
