---
- name: Install Tailscale
  hosts: '{{ vm_hosts | default("all")}}'
  gather_facts: true
  become: true
  roles:
    - role: artis3n.tailscale.machine
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
