---
roles:
  - name: geerlingguy.node_exporter
    version: 2.1.1
  - name: geerlingguy.docker
    version: 7.4.7
  - name: artis3n.tailscale
    version: v5.0.1
  - name: robertdebock.collectd
    version: 3.1.8
collections:
  - community.general
  - victoriametrics.cluster
