---
roles:
  - name: geerlingguy.node_exporter
    version: 2.2.0
  - name: geerlingguy.docker
    version: 8.0.0
  - name: robertdebock.collectd
    version: 3.1.8
collections:
  - community.general
  - ansible.posix
  - community.docker
  - name: artis3n.tailscale
  - victoriametrics.cluster
