---
- name: Create database using custom credentials
  hosts: '{{ vm_hosts | default("influxdb")}}'
  become: true
  gather_facts: true
  tasks:
    - name: Install influxdb
      community.general.influxdb_database:
        hostname: something
        username: root
        password: greatgreatgreat
        database_name: proxmox
        validate_certs: true
