---
name: Cleanup old container images

'on':
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete old untagged runner container versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'homelab/github-runner'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: true

      - name: Delete old untagged CI container versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'homelab/ci'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: true
