---
name: lint
"on":
  push:
    paths:
      - "ansible/**"
      - ".github/workflows/lint.yaml"
jobs:
  secret-detection:
    runs-on: [self-hosted, Linux, X64, playground-ubuntu]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run gitleaks
        run: gitleaks detect --source . --verbose

  lint:
    name: Linting
    runs-on: [self-hosted, Linux, X64, playground-ubuntu]
    steps:
      - uses: actions/checkout@v6
      - name: Install Ansible Deps
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          uv run --python 3.14 --with ansible-core ansible-galaxy collection install -v -r ansible/requirements.yml
          uv run --python 3.14 --with ansible-core ansible-galaxy role install -v -r ansible/requirements.yml
      - name: Lint code with yamllint
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          make lint-ansible
