---
name: lint
"on": push
jobs:
  lint:
    name: Linting
    runs-on: [self-hosted, Linux, X64, playground-ubuntu]
    steps:
      - uses: actions/checkout@v6
      - name: Install Ansible Deps
        run: |
          uv run --python 3.14 --with ansible-core ansible-galaxy collection install -v -r ansible/requirements.yml
          uv run --python 3.14 --with ansible-core ansible-galaxy role install -v -r ansible/requirements.yml
      - name: Lint code with yamllint
        run: make lint-ansible
